Добавлен UserProfileController.
PetSocialNetwork/PetSocialNetwork pull request #11
Opened 2024-06-26 13:51 UTC by PavelTitushkin

Closes #7 #8

2024-06-26 16:07 UTC, KhristinaVorozhbet93 commented on sources/PetSocialNetwork.API/Controllers/UserProfileController.cs
> +        public async Task<UserProfile> Create(UserProfile profile, CancellationToken cancellationToken)
Думаю, тут должна прийти в параметрах не сущность UserProfile, а, например, какой-нибудь UserProfleRequest. Из него уже будем брать параметры и создавать сущность UserProfile, используя модель для передачи данных, а не саму сущность.

2024-06-26 16:09 UTC, KhristinaVorozhbet93 commented on sources/PetSocialNetwork.API/Controllers/UserProfileController.cs
> +        {
В конструкторе тоже нужно валидировать сервисы и выбросить exception

2024-06-26 16:20 UTC, KhristinaVorozhbet93 commented on sources/PetSocialNetwork.API/Controllers/UserProfileController.cs
> +                throw new ValidationException(result.Errors);
В контроллерах, в основном не кидаем exception (только в исключительных ситуациях, как в конструкторе, так как дальнейшие действия без сервисов будут невозможны), а  в самом методе действия контроллера мы обычно возвращаем статус код. Например, return OK() или BadRequest()(и другие).

2024-06-26 16:24 UTC, KhristinaVorozhbet93 commented on sources/PetSocialNetwork.API/Controllers/UserProfileController.cs
> +                 .FirstOrDefaultAsync(u => u.Id == id, cancellationToken);
Вот здесь такая же история, мы любо вернем первый попавший профиль, либо вообще вернем null. Как минимум, я бы сделала SingleOrDefaultAsync, потому что вряд ли у нас буду в бд 2 профиля с одинаковыми id. И если бы из бд вернулось null, то нужно выкинуть код ответа, а не exception. Иначе у нас будет ошибка на стороне сервера, а по факту скорее всего клиент неправильно предоставил данные для получения профиля(ошибка на стороне клиента).

2024-06-26 16:48 UTC, KhristinaVorozhbet93 commented on sources/PetSocialNetwork.API/Controllers/UserProfileController.cs
> +        public async Task<UserProfile?> Get(Guid id, CancellationToken cancellationToken)
Также возращаем Task<ActionResult<UserProfileResponse>

2024-06-28 10:45 UTC, toxic-sunflower commented on sources/PetSocialNetwork.API/Controllers/UserProfileController.cs
> +                 .FirstOrDefaultAsync(u => u.Id == id, cancellationToken);
@KhristinaVorozhbet93, @PavelTitushkin, посмотрел. Вердикт остаётся без изменений.

2024-06-28 11:36 UTC, toxic-sunflower requested changes
Написал комментарии. Просьба: пиши, пожалуйста в сообщение при создании PR краткое summary по сделанному.

2024-06-28 11:36 UTC, toxic-sunflower commented on sources/PetSocialNetwork.API/Controllers/UserProfileController.cs
> +                Data = entity,
Давай не вводить лишних абстракций.

Просто создай класс, например, UserProfileResponse, добавь в него нужные свойства и возвращай его.

2024-06-28 11:36 UTC, toxic-sunflower commented on sources/PetSocialNetwork.API/DTOs/LinkDTO.cs
> +    public class LinkDTO
Вот этот класс пока оставь, он скорее всего понадобится.

2024-06-28 11:36 UTC, toxic-sunflower commented on sources/PetSocialNetwork.API/DTOs/RestDTO.cs
> +    public class RestDTO<T>
А вот этот класс давай перепишем. Вообще говоря, создать базовый тип для ответов -- идея хорошая, но давай создадим именно базовый класс, а не generic-тип. 

Пока создай пустой тип _ResponseBase_, от него унаследуй UserProfileResponse.

PageIndex, PageSize, RecordCount по хорошему нужны, когда мы возвращаем коллекцию, а не один результат, например, при пейджинге.

2024-06-28 11:36 UTC, toxic-sunflower commented on sources/PetSocialNetwork.API/DTOs/UserProfileDTO.cs
> +    public class UserProfileDTO
Создай 2 типа: UserProfileRequest и UserProfileResponse. Данные, которые мы отправляем клиенту могут отличаться от тех, что мы принимаем от него при сохранении профиля.

2024-06-28 11:36 UTC, toxic-sunflower commented on sources/PetSocialNetwork.API/Program.cs
> +using PetSocialNetwork.API.DTOs;
Давай не использовать постфикс DTO, а использовать Request и Response. Для них давай создадим папочку Contracts (это, честно говоря, гораздо звучнее, чем и Models и DTOs)

2024-06-28 11:36 UTC, toxic-sunflower commented on sources/PetSocialNetwork.API/Program.cs
> +
Используй метод расширения AddFluentValidation

2024-06-28 11:36 UTC, toxic-sunflower commented on sources/PetSocialNetwork.API/Validators/UserProfileValidator.cs
> +            RuleFor(x => x.Animal).NotNull().NotEmpty();
1. Если используешь правило NotEmpty, NotNull не нужен, на null проверяется автоматически.

2. Давай добавим сообщения об ошибках, это делается методом расширения WithMessage

2024-06-28 11:36 UTC, toxic-sunflower commented on sources/PetSocialNetwork.API/appsettings.Development.json
> +    "Default": "Host=localhost;Port=5432;Database=PetSocialNetwork;Username=postgres;Password=1234",
Вот это надо откатить.

2024-06-30 10:30 UTC, KhristinaVorozhbet93 commented on sources/PetSocialNetwork.API/Program.cs
> +            //builder.Services.AddScoped<IValidator<UserProfileDTO>, UserProfileValidator>();
Давай прям удалять ненужные регистрации, а не добавлять их в комментарии)

2024-06-30 14:54 UTC, merged